### ISSUE TITLE
Can't copy console input, and can't even select output (that is also broken in notebook)

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#355]
In the console, if I select an input block, copying is disabled (`Cmd-C` doesn't work, and even the browser's context menu shows it disabled):

![image](https://cloud.githubusercontent.com/assets/57394/16793602/09338ebe-4887-11e6-8bbe-b107a6018c9d.png)

Furthermore, output can't even be highlighted at all.

In the notebook, input selection/copy do work, but output also can't be selected.

**Comment by sccolbert** [comment]
This is due to the base CSS in `phosphor-widget` setting `user-select: none;`. That's an overly-aggressive default, and is fixed in the `phosphor` mono-repo. This problem will go away once we transition to that repo.

**Comment by fperez** [comment]
Good to know, thanks!

**Comment by blink1073** [comment]
Fixed by #591.

**Comment by fperez** [comment]
Hey @blink1073, thanks for working on this! But I'm still seeing a problem on master from today...

As you can see in this gif:

![console](https://cloud.githubusercontent.com/assets/57394/17573419/23380a12-5f0f-11e6-9bdb-7c0e6eaa6f28.gif)

upon trying to select any output, it instantly gets de-selected the moment I release the mouse button.  So it's impossible to actually copy to the clipboard...

Can you replicate? If so, let's reopen...

**Comment by fperez** [comment]
BTW, I should clarify that I only see the above problem in the console, the notebook is fine.

**Comment by blink1073** [comment]
This is fixed in #636 by not activating the prompt on click events.  We still can't select the *input* text.  I can't figure out how to get the inactive codemirror outputs to allow copying text reliably.  This could be solved by rendering inactive codemirror outputs, which is something we intend to add.

**Comment by fperez** [comment]
Reopening, as on master (b99060f), I'm seeing it again... I can copy output (printed and displayed in `Out[..]` area), but I can't copy from the input area. I can select, but not copy.

**Comment by fperez** [comment]
I should add that on @Carreau's advice, I just nuked and rebuilt from scratch my entire JLab install, just in case the recent phosphor changes to a mono-repo were not propagating correctly.  The problem persists.

**Comment by blink1073** [comment]
See my previous comment.

**Comment by fperez** [comment]
Ah, sorry! I missed the part of your comment where you specifically addressed the input part :)

Opened #679 to track just that question as this issue has a bunch of other stuff in it that's now been resolved.
