### ISSUE TITLE
Test failure in Chrome

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#57]
I also see this error on 4e59585dfdc334286bb3fbc1b4ffd6c702c8a4d2 when doing `npm run test:chrome` (but not under firefox). I've replaced the system path to the jupyterlab repo with `<<<PATH>>>`.

```
FAILED TESTS:
  jupyter-ui
    PDFRenderer
      ✖ should output the correct HTML
        Chrome 51.0.2704 (Mac OS X 10.10.5)
      Error: expected '<a target="_blank" href="data:application/pdf;<<PATH>>64,I don\'t have a b64\'d PDF">View PDF</a>' to equal '<a href="data:application/pdf;<<PATH>>64,I don\'t have a b64\'d PDF" target="_blank">View PDF</a>'
          at Assertion.assert (<<PATH>>/test/build/bundle.js:309:14)
          at Assertion.be.Assertion.equal (<<PATH>>/test/build/bundle.js:429:11)
          at Assertion.(anonymous function) [as be] (<<PATH>>/test/build/bundle.js:282:25)
          at Context.<anonymous> (<<PATH>>/test/build/bundle.js:25369:42)
```

**Comment by blink1073** [comment]
This will be fixed by #56.

**Comment by blink1073** [comment]
(I made the test less brittle).

**Comment by blink1073** [comment]
Fixed by #56.

**Comment by jasongrout** [comment]
But we still have the problem that the path is appearing where it definitely should not appear, right? Shouldn't we be checking for `data:application/pdf;base64,I don\'t have a b64\'d PDF`?

**Comment by blink1073** [comment]
Looks that way: https://github.com/nteract/transformime-jupyter-transformers/blob/master/test/pdf.transform.test.js#L27

**Comment by jasongrout** [comment]
Yeah, they have problem as well. Our problem also stemmed from the order of the html attributes being different in the test vs the reference string.

**Comment by ellisonbg** [comment]
@jasongrout and @blink1073 what is the status of this one?

**Comment by blink1073** [comment]
It is still a bug, 0.9 is a fair milestone.
