### ISSUE TITLE
node build error after updating to latest

### ISSUE THREAD

**Issue by dhirschfeld** [jupyter/jupyterlab#715]
```
(py-dev) C:\dev\code\jupyterlab (master) (jupyterlab@0.2.0)
λ pip install --no-deps -e .
Obtaining file:///C:/dev/code/jupyterlab
    Complete output from command python setup.py egg_info:
    setup.py entered
    running egg_info
    running jsdeps
    3.8.9
<SNIP>
    > jupyterlab-extension@0.1.0 build:extension C:\dev\code\jupyterlab\jupyterlab
    > webpack

    Generating config...
    Generating bundles...
    ModuleParseError: Module parse failed: C:\dev\code\jupyterlab\jupyterlab\build\jupyterlab-shim.js Bad character escape sequence (91:23)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Bad character escape sequence (91:23)
        at Parser.pp$4.raise (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp$7.readHexChar (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:3037:26)
        at Parser.pp$7.readCodePoint (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2913:19)
        at Parser.pp$7.readEscapedChar (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:3005:45)
        at Parser.pp$7.readString (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2935:23)
        at Parser.pp$7.getTokenFromCode (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2724:19)
        at Parser.pp$7.readToken (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2477:17)
        at Parser.pp$7.nextToken (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2468:15)
        at Parser.pp$7.next (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2413:10)
        at Parser.pp.eat (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:536:12)
        at Parser.pp$3.parseSubscripts (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1731:25)
        at Parser.pp$3.parseExprSubscripts (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1718:17)
        at Parser.pp$3.parseMaybeUnary (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1692:19)
        at Parser.pp$3.parseExprOps (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1637:21)
        at Parser.pp$3.parseMaybeConditional (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1620:21)
        at Parser.pp$3.parseMaybeAssign (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1597:21)
        at Parser.pp$3.parseExpression (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1573:21)
        at Parser.pp$1.parseStatement (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:727:47)
        at Parser.pp$1.parseTopLevel (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:638:25)
        at Parser.parse (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:516:17)
        at Object.parse (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.finished (C:\dev\code\jupyterlab\jupyterlab\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
        at C:\dev\code\jupyterlab\jupyterlab\node_modules\graceful-fs\graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
        at DependenciesBlock.<anonymous> (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack\lib\NormalModule.js:113:20)
        at DependenciesBlock.onModuleBuild (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.finished (C:\dev\code\jupyterlab\jupyterlab\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
        at C:\dev\code\jupyterlab\jupyterlab\node_modules\graceful-fs\graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:extension"
    npm ERR! node v6.2.0
    npm ERR! npm  v3.8.9
    npm ERR! code ELIFECYCLE
    npm ERR! jupyterlab-extension@0.1.0 build:extension: `webpack`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab-extension@0.1.0 build:extension script 'webpack'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab-extension package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     webpack
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab-extension
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab-extension
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\dev\code\jupyterlab\jupyterlab\npm-debug.log

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
    npm ERR! node v6.2.0
    npm ERR! npm  v3.8.9
    npm ERR! code ELIFECYCLE
    npm ERR! jupyterlab-extension@0.1.0 build: `npm run update && npm run build:extension`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab-extension@0.1.0 build script 'npm run update && npm run build:extension'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab-extension package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run update && npm run build:extension
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab-extension
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab-extension
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\dev\code\jupyterlab\jupyterlab\npm-debug.log

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:serverextension"
    npm ERR! node v6.2.0
    npm ERR! npm  v3.8.9
    npm ERR! code ELIFECYCLE
    npm ERR! jupyterlab@0.2.0 build:serverextension: `cd jupyterlab && npm run build && cd ..`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab@0.2.0 build:serverextension script 'cd jupyterlab && npm run build && cd ..'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     cd jupyterlab && npm run build && cd ..
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\dev\code\jupyterlab\npm-debug.log
    C:\Python\envs\py-dev\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'License'
      warnings.warn(msg)
    rebuilding js and css failed
    missing files: ['C:\\dev\\code\\jupyterlab\\jupyterlab\\build\\jupyterlab.css', 'C:\\dev\\code\\jupyterlab\\jupyterlab\\build\\jupyterlab.bundle.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\dev\code\jupyterlab\setup.py", line 173, in <module>
        setup(**setup_args)
      File "C:\Python\envs\py-dev\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python\envs\py-dev\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python\envs\py-dev\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\code\jupyterlab\setup.py", line 55, in run
        raise e
      File "C:\dev\code\jupyterlab\setup.py", line 48, in run
        self.distribution.run_command('jsdeps')
      File "C:\Python\envs\py-dev\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\code\jupyterlab\setup.py", line 116, in run
        run('npm run build:serverextension')
      File "C:\dev\code\jupyterlab\setup.py", line 29, in run
        check_call(cmd.split(), shell=shell, cwd=cwd, stdout=sys.stdout, stderr=sys.stderr)
      File "C:\Python\envs\py-dev\lib\subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['npm', 'run', 'build:serverextension']' returned non-zero exit status 1
```

**Comment by dhirschfeld** [comment]
`npm-debug.log`
```
(py-dev) C:\dev\code\jupyterlab (master) (jupyterlab@0.2.0)
λ cat  C:\dev\code\jupyterlab\jupyterlab\npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle jupyterlab-extension@0.1.0~prebuild: jupyterlab-extension@0.1.0
6 silly lifecycle jupyterlab-extension@0.1.0~prebuild: no script for prebuild, continuing
7 info lifecycle jupyterlab-extension@0.1.0~build: jupyterlab-extension@0.1.0
8 verbose lifecycle jupyterlab-extension@0.1.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle jupyterlab-extension@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\dev\code\jupyterlab\jupyterlab\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\dev\code\jupyterlab\node_modules\.bin;C:\Program Files\nodejs;C:\Python\envs\py-dev\Library\bin;C:\Python\envs\py-dev\Library\bin;C:\Python\envs\py-dev;C:\Python\envs\py-dev\Scripts;C:\Python\envs\py-dev;C:\Python\envs\py-dev\Scripts;C:\Python\envs\py-dev;C:\Python\envs\py-dev\Library\mingw-w64\bin;C:\Python\envs\py-dev\Library\usr\bin;C:\Python\envs\py-dev\Library\bin;C:\Python\envs\py-dev\Scripts;C:\Python\envs\py-dev;C:\Python\envs\py-dev\Scripts;H:\bin\cmder\bin;C:\Program Files\Git\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\share\vim\vim74;H:\bin\cmder\vendor\conemu-maximus5;H:\bin\cmder\vendor\conemu-maximus5\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\avs\bin;C:\Oracle\product\11.2.0\client_x64\bin;C:\Oracle\product\11.2.0\client_x86\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Python;C:\Python\Scripts;C:\Python\Library\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs;C:\Program Files\Internet Explorer;C:\bin\Redis\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\bin\pandoc\;C:\Program Files\nodejs\;C:\Program Files\TortoiseGit\bin;C:\Octave\Octave-4.0.3;C:\Users\dhirschf\AppData\Local\atom\bin;C:\Users\dhirschf\AppData\Roaming\npm;H:\bin\cmder
10 verbose lifecycle jupyterlab-extension@0.1.0~build: CWD: C:\dev\code\jupyterlab\jupyterlab
11 silly lifecycle jupyterlab-extension@0.1.0~build: Args: [ '/d /s /c', 'npm run update && npm run build:extension' ]
12 silly lifecycle jupyterlab-extension@0.1.0~build: Returned: code: 1  signal: null
13 info lifecycle jupyterlab-extension@0.1.0~build: Failed to exec build script
14 verbose stack Error: jupyterlab-extension@0.1.0 build: `npm run update && npm run build:extension`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid jupyterlab-extension@0.1.0
16 verbose cwd C:\dev\code\jupyterlab\jupyterlab
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.2.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error jupyterlab-extension@0.1.0 build: `npm run update && npm run build:extension`
22 error Exit status 1
23 error Failed at the jupyterlab-extension@0.1.0 build script 'npm run update && npm run build:extension'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the jupyterlab-extension package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run update && npm run build:extension
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs jupyterlab-extension
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls jupyterlab-extension
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by blink1073** [comment]
Hi @dhirschfeld, can you paste the contents of the `C:\dev\code\jupyterlab\jupyterlab\build\jupyterlab-shim.js` file?

**Comment by ellisonbg** [comment]
I am also seeing these errors:

```
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ../jade/jade in /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/jupyterlab/node_modules/codemirror/mode/vue
    at /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (/Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (/Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
resolve file
  /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/jupyterlab/node_modules/codemirror/mode/jade/jade.webpack.js doesn't exist
  /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/jupyterlab/node_modules/codemirror/mode/jade/jade doesn't exist
  /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/jupyterlab/node_modules/codemirror/mode/jade/jade.web.js doesn't exist
  /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/jupyterlab/node_modules/codemirror/mode/jade/jade.js doesn't exist
  /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/jupyterlab/node_modules/codemirror/mode/jade/jade.json doesn't exist
resolve directory
  /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/jupyterlab/node_modules/codemirror/mode/jade/jade doesn't exist (directory default file)
  /Users/bgranger/github/jupyter/jupyterlab/jupyterlab/node_modules/jupyterlab/node_modules/codemirror/mode/jade/jade/package.json doesn't exist (directory description file)
```

**Comment by dhirschfeld** [comment]
@blink1073 - sorry I should have thought of that.

I've pushed the build artifacts to a [branch](https://github.com/dhirschfeld/jupyterlab/tree/build-artifacts) on my fork. [`jupyterlab-shim.js`](https://github.com/dhirschfeld/jupyterlab/blob/build-artifacts/jupyterlab/build/jupyterlab-shim.js) looked normal to me, even when viewing with invisibles showing in my editor. Maybe you can spot something obvious?

**Comment by jasongrout** [comment]
This should be fixed now with https://github.com/jupyter/jupyterlab/commit/ad9af37d482a9a9df4d9f543ce522ab4b72eda1e. Can you check?

**Comment by dhirschfeld** [comment]
@jasongrout - didn't seem to make a difference - still getting a bad character escape sequence which I think may be different to the code mirror issues? Likely to do with me being on Windows I guess :/

Am doing a `git clean -fdx` and will give another go...

**Comment by dhirschfeld** [comment]
no joy:
https://github.com/dhirschfeld/jupyterlab/blob/build-artifacts/jupyterlab/build/jupyterlab-shim.js
```
    > jupyterlab-extension@0.1.0 build:extension C:\dev\code\jupyterlab\jupyterlab
    > webpack

    Generating config...
    Generating bundles...
    ModuleParseError: Module parse failed: C:\dev\code\jupyterlab\jupyterlab\build\jupyterlab-shim.js Bad character escape sequence (81:23)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Bad character escape sequence (81:23)
        at Parser.pp$4.raise (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp$7.readHexChar (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:3037:26)
        at Parser.pp$7.readCodePoint (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2913:19)
        at Parser.pp$7.readEscapedChar (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:3005:45)
        at Parser.pp$7.readString (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2935:23)
        at Parser.pp$7.getTokenFromCode (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2724:19)
        at Parser.pp$7.readToken (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2477:17)
        at Parser.pp$7.nextToken (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2468:15)
        at Parser.pp$7.next (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:2413:10)
        at Parser.pp.eat (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:536:12)
        at Parser.pp$3.parseSubscripts (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1731:25)
        at Parser.pp$3.parseExprSubscripts (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1718:17)
        at Parser.pp$3.parseMaybeUnary (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1692:19)
        at Parser.pp$3.parseExprOps (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1637:21)
        at Parser.pp$3.parseMaybeConditional (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1620:21)
        at Parser.pp$3.parseMaybeAssign (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1597:21)
        at Parser.pp$3.parseExpression (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:1573:21)
        at Parser.pp$1.parseStatement (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:727:47)
        at Parser.pp$1.parseTopLevel (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:638:25)
        at Parser.parse (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:516:17)
        at Object.parse (C:\dev\code\jupyterlab\jupyterlab\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.finished (C:\dev\code\jupyterlab\jupyterlab\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
        at C:\dev\code\jupyterlab\jupyterlab\node_modules\graceful-fs\graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
        at DependenciesBlock.<anonymous> (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack\lib\NormalModule.js:113:20)
        at DependenciesBlock.onModuleBuild (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at C:\dev\code\jupyterlab\jupyterlab\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.finished (C:\dev\code\jupyterlab\jupyterlab\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
        at C:\dev\code\jupyterlab\jupyterlab\node_modules\graceful-fs\graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

**Comment by dhirschfeld** [comment]
I'll update node and try again - figure it can't hurt...

**Comment by blink1073** [comment]
Your generated shim file has backslashes where mine (on OSX) has forward slashes.  It looks like we need to update the paths returned by `require.resolve` to use forward slashes regardless of platform.

**Comment by blink1073** [comment]
Specifically, here: https://github.com/jupyter/jupyterlab/blob/b367cb8a0c24cefaea12c02768e9567085b3bb62/scripts/extension_helpers.js#L73

**Comment by blink1073** [comment]
Or, perhaps we just need to use `path.posix.join` here: https://github.com/jupyter/jupyterlab/blob/b367cb8a0c24cefaea12c02768e9567085b3bb62/scripts/extension_helpers.js#L116

**Comment by blink1073** [comment]
@dhirschfeld, can you try a global replace of `path.` -> `path.posix.` in that file and see if it fixes your build?

**Comment by dhirschfeld** [comment]
Will give it a go...

**Comment by blink1073** [comment]
This highlights the issue that we need to enable Appveyor testing.

**Comment by dhirschfeld** [comment]
Replacing all `path.` with `path.posix.` seemed to get a lot further but finally failed with:
```
      |   +-- async-each@1.0.0
      |   +-- glob-parent@2.0.0
      |   +-- is-binary-path@1.0.1
      |   | `-- binary-extensions@1.5.0
      |   +-- is-glob@2.0.1
      |   | `-- is-extglob@1.0.0
      |   `-- readdirp@2.1.0
      |     `-- set-immediate-shim@1.0.1
      `-- webpack-core@0.6.8
        `-- source-map@0.4.4
          `-- amdefine@1.0.0

    npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

    > jupyterlab@0.2.0 build:serverextension C:\dev\code\jupyterlab
    > npm run build:css && cd jupyterlab && npm run build && cd ..


    > jupyterlab@0.2.0 build:css C:\dev\code\jupyterlab
    > concurrently "npm run build:css:base" "npm run build:css:theme"

    [1]
    [1] > jupyterlab@0.2.0 build:css:theme C:\dev\code\jupyterlab
    [1] > lessc src/default-theme/index.less src/default-theme/index.css
    [1]
    [0]
    [0] > jupyterlab@0.2.0 build:css:base C:\dev\code\jupyterlab
    [0] > lessc src/basestyle/index.less src/basestyle/index.css
    [0]
    [0] npm run build:css:base exited with code 0
    [1] npm run build:css:theme exited with code 0

    > jupyterlab-extension@0.1.0 build C:\dev\code\jupyterlab\jupyterlab
    > npm run update && npm run build:extension


    > jupyterlab-extension@0.1.0 update C:\dev\code\jupyterlab\jupyterlab
    > rimraf node_modules/jupyterlab && npm install


    > jupyterlab@0.2.0 prepublish C:\dev\code\jupyterlab
    > npm run build


    > jupyterlab@0.2.0 build C:\dev\code\jupyterlab
    > npm run build:css && npm run build:src


    > jupyterlab@0.2.0 build:css C:\dev\code\jupyterlab
    > concurrently "npm run build:css:base" "npm run build:css:theme"

    [0]
    [0] > jupyterlab@0.2.0 build:css:base C:\dev\code\jupyterlab
    [0] > lessc src/basestyle/index.less src/basestyle/index.css
    [0]
    [1]
    [1] > jupyterlab@0.2.0 build:css:theme C:\dev\code\jupyterlab
    [1] > lessc src/default-theme/index.less src/default-theme/index.css
    [1]
    [0] npm run build:css:base exited with code 0
    [1] npm run build:css:theme exited with code 0

    > jupyterlab@0.2.0 build:src C:\dev\code\jupyterlab
    > tsc --project src && node scripts/copyfiles.js


    > jupyterlab@0.2.0 postinstall C:\dev\code\jupyterlab\jupyterlab\node_modules\jupyterlab
    > node scripts/dedupe.js


    > jupyterlab-extension@0.1.0 postinstall C:\dev\code\jupyterlab\jupyterlab
    > node ../scripts/dedupe.js

    jupyterlab-extension@0.1.0 C:\dev\code\jupyterlab\jupyterlab
    `-- jupyterlab@0.2.0

    npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

    > jupyterlab-extension@0.1.0 build:extension C:\dev\code\jupyterlab\jupyterlab
    > webpack

    Generating config...
    fs.js:951
      return binding.readdir(pathModule._makeLong(path), options.encoding);
                     ^

    Error: ENOENT: no such file or directory, scandir 'C:\dev\code\jupyterlab\jupyterlab\lib'
        at Error (native)
        at Object.fs.readdirSync (fs.js:951:18)
        at _walkSync (C:\dev\code\jupyterlab\jupyterlab\node_modules\walk-sync\index.js:64:18)
        at Function.entries (C:\dev\code\jupyterlab\jupyterlab\node_modules\walk-sync\index.js:40:10)
        at Object.createShim (C:\dev\code\jupyterlab\jupyterlab\node_modules\jupyterlab\scripts\extension_helpers.js:110:26)
        at Object.<anonymous> (C:\dev\code\jupyterlab\jupyterlab\webpack.config.js:30:22)
        at Module._compile (module.js:556:32)
        at Object.Module._extensions..js (module.js:565:10)
        at Module.load (module.js:473:32)
        at tryModuleLoad (module.js:432:12)

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\bin\\nodejs\\node.exe" "C:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:extension"
    npm ERR! node v6.4.0
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE
    npm ERR! jupyterlab-extension@0.1.0 build:extension: `webpack`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab-extension@0.1.0 build:extension script 'webpack'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab-extension package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     webpack
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab-extension
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab-extension
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\dev\code\jupyterlab\jupyterlab\npm-debug.log

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\bin\\nodejs\\node.exe" "C:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
    npm ERR! node v6.4.0
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE
    npm ERR! jupyterlab-extension@0.1.0 build: `npm run update && npm run build:extension`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab-extension@0.1.0 build script 'npm run update && npm run build:extension'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab-extension package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run update && npm run build:extension
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab-extension
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab-extension
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\dev\code\jupyterlab\jupyterlab\npm-debug.log

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\bin\\nodejs\\node.exe" "C:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:serverextension"
    npm ERR! node v6.4.0
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE
    npm ERR! jupyterlab@0.2.0 build:serverextension: `npm run build:css && cd jupyterlab && npm run build && cd ..`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab@0.2.0 build:serverextension script 'npm run build:css && cd jupyterlab && npm run build && cd ..'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run build:css && cd jupyterlab && npm run build && cd ..
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\dev\code\jupyterlab\npm-debug.log
    C:\Python\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'License'
      warnings.warn(msg)
    rebuilding js and css failed
    missing files: ['C:\\dev\\code\\jupyterlab\\jupyterlab\\build\\jupyterlab.css', 'C:\\dev\\code\\jupyterlab\\jupyterlab\\build\\jupyterlab.bundle.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\dev\code\jupyterlab\setup.py", line 173, in <module>
        setup(**setup_args)
      File "C:\Python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\code\jupyterlab\setup.py", line 55, in run
        raise e
      File "C:\dev\code\jupyterlab\setup.py", line 48, in run
        self.distribution.run_command('jsdeps')
      File "C:\Python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\code\jupyterlab\setup.py", line 116, in run
        run('npm run build:serverextension')
      File "C:\dev\code\jupyterlab\setup.py", line 29, in run
        check_call(cmd.split(), shell=shell, cwd=cwd, stdout=sys.stdout, stderr=sys.stderr)
      File "C:\Python\lib\subprocess.py", line 584, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['npm', 'run', 'build:serverextension']' returned non-zero exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\dev\code\jupyterlab\
```

**Comment by blink1073** [comment]
Shucks, I'll have to boot my Windows machine in the morning and get this working.   Sorry for the frustration.

**Comment by dhirschfeld** [comment]
No worries - thanks for looking into it. It case it helps the latest build artifacts are at
https://github.com/dhirschfeld/jupyterlab/tree/build-artifacts

**Comment by dhirschfeld** [comment]
This time the build directory was deleted and there exists a `jupyterlab/lib` folder, but no `jupyterlab/jupyterlab/lib` folder as appears to be specified in the error message:

`Error: ENOENT: no such file or directory, scandir 'C:\dev\code\jupyterlab\jupyterlab\lib'`

**Comment by dhirschfeld** [comment]
Success! :tada: 

I tried a slightly more conservative approach of only replacing `path.join` with `path.posix.join`, cleaned my checkout and rebuilt and it worked!
````
git clean -xdf
npm update
pip install -e .
```

I put my changes up in PR #721

**Comment by dhirschfeld** [comment]
Not quite out of the woods yet as actually running jupyterlab doesn't display anything in the browser with the below errors in the javasxript console:
![image](https://cloud.githubusercontent.com/assets/881019/17875483/d9f3c420-6915-11e6-8dad-b00fa5b97ee5.png)

Is anyone else seeing any problems with the latest master?

**Comment by blink1073** [comment]
I think @eskirk saw this same problem yesterday.
